### PR TITLE
add search component with option to be clearable

### PR DESCRIPTION
**Pull request by rfarine**
Default
screen shot 2017-04-24 at 3 49 46 pm

Focused and with Text
screen shot 2017-04-24 at 3 49 56 pm

With Instructions
screen shot 2017-04-24 at 3 50 03 pm

With Clearable Icon
screen shot 2017-04-24 at 3 50 11 pm

Disabled
screen shot 2017-04-24 at 3 50 17 pm

### CODE REVIEW

**Comment by nickstamas** [comment]
@rfarine This looks good. One question, do you think there's enough of a difference between a Search component and a TextInput component to justify a new component vs moving the logic into TextInput? I'm fine with either, and I'm not sure how I feel about it either way. What do you think?

**Comment by rfarine** [comment]
@nickstamas There's a lot of other features that the Search component is going to need.. like a dropdown for autocomplete, etc... so I created this for the future of the  component.

**Comment by nickstamas** [comment]
@rae True, I guess it starts to overload a TextInput with a lot of stuff going forward. Thanks for adding this :)

**Comment by rfarine** [comment]
@nickstamas No worries! :D

**Comment by nickstamas** [comment]
👍

**Pull request merged**
