### PR TITLE
Fix Unknown prop `description` on <input> tag console warning

### PR DESCRIPTION
**Pull request by aaroncouture**
This fixes a prop warning on the RadioButton component.. description is not a valid prop for input.

### CODE REVIEW

**Comment by kangax** [comment]
Should it be removed from `RadioButton.propTypes` as well?

**Comment by kangax** [comment]
I also wonder what was the purpose of this in the first place. Should we use "title" attribute instead? To show tooltip with a hint.

**Comment by aaroncouture** [comment]
@kangax the description prop is being used in the component (it is being rendered into a span). Not sure why it was also being passed into the input tag as well (since that isnt a supported attribute). In short, that propType is still needed.

**Comment by kangax** [comment]
Ah, I see. Makes sense then.

**Pull request merged**
